version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "muimijohn52-bot"
    labels:
      - "dependencies"
      - "npm"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"
